### ISSUE TITLE
Дубляж кода

### ISSUE THREAD

**Issue by boris-dev** [willstay/liga-internship#1]
Также это тестовый метод в продакшкене, может он вообще не нужен?

https://github.com/willstay/liga-internship/blob/9db7f78db63452477913c264b6eac6791ac9560f/javacore-song-task/src/main/java/ru/liga/songtask/domain/DoAnalyze.java#L10

**Comment by willstay** [comment]
Все верно, он устарел, не успел его ещё удалить. Исправил.
