### ISSUE TITLE
С полным путём до файла работает? C:\users\blablabla\song.mid

### ISSUE THREAD

**Issue by boris-dev** [willstay/liga-internship#9]
https://github.com/willstay/liga-internship/blob/809a00948dfe7ae765e30ddc3dfcb396b671afb3/javacore-song-task/src/main/java/ru/liga/songtask/analyzer/DoAnalyze.java#L13

**Comment by willstay** [comment]
Если я правильно помню, по заданию надо было использовать ресурсы. Для гибкости сделал так, что DoAnalyze теперь принимает File, а не имя файла.
